name: Build and Deploy
on:
  push:
    branches:
      - main # If your default branch is named something else, change this

permissions:
  contents: write
  pages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          override: true

      - name: Build
        run: cargo build --release --target wasm32-unknown-unknown

      - name: Debug - Check if build succeeded
        run: |
          echo "=== Build completed, checking what was created ==="
          echo "Current directory contents:"
          ls -la
          echo ""
          echo "Target directory contents:"
          ls -la ./target/ || echo "No target directory found"
          echo ""
          echo "Target wasm32-unknown-unknown contents:"
          ls -la ./target/wasm32-unknown-unknown/ || echo "No wasm32-unknown-unknown directory found"
          echo ""
          echo "Target wasm32-unknown-unknown/release contents:"
          ls -la ./target/wasm32-unknown-unknown/release/ || echo "No release directory found"
          echo ""
          echo "Looking for any .wasm files anywhere:"
          find . -name "*.wasm" -type f || echo "No .wasm files found"
          echo ""
          echo "Cargo.toml contents:"
          cat Cargo.toml

      - name: Prepare Deployment Directory
        run: |
          mkdir -p ./deploy
          cp ./target/wasm32-unknown-unknown/release/Assignment-Gravity-Sim.wasm ./deploy/
          cp index.html ./deploy/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./deploy
